# Generated by Django 6.0.1 on 2026-02-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile_last_fetch_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True)),
                ('readings', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
