# Generated by Django 6.0.1 on 2026-02-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_userprofile_plan_userprofile_plan_expires_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
